### ISSUE TITLE
Suggestion add firmware downloader

### ISSUE THREAD

**Issue by ginkuji** [eXhumer/patches#1]
Hi i would like to suggest adding firmware downloader from darthsternie site. This could make you homebrew an all in one essential app. Thank you. Please consider my proposal.

**Comment by HyperLemons** [comment]
How the hell does sigpatches + sys firmware make a "AIO essential" app?

**Comment by ginkuji** [comment]
Well, It can be useful for others who simply want to download firmware files directly to their units since they are banned. This is just a suggestion. No need to go all the way to "hell" just to state your point.

**Comment by eXhumer** [comment]
This is something I will actually look later, just not now. I am building my own updater application using borealis to replace my fork of atmosphere-updater.

**Comment by eXhumer** [comment]
Also, not an issue regarding this project. Closing.
