### ISSUE TITLE
1.15.0 atmosphere patches when?

### ISSUE THREAD

**Issue by GamingInfinite** [eXhumer/patches#2]
sorry if this seems a bit forthcoming, but I just updated my cfw and then realized "oh wait, patches don't work" and then wanted to ask if and when the 0.15-atmosphere patches would be available.  This is purely for having a timeframe, and I don't know how hard it is to make the patches so if it's a whole ass 3 months, that's fine by me.

**Comment by arch-box** [comment]
Nearly a month ago: https://github.com/ITotalJustice/patches/releases/latest/

**Comment by Nazosan** [comment]
Different project by a different person, but thanks for the link.

**Comment by DreamDevourer** [comment]
I tested this patch with 1.13, 10.14, 1.14.4 and also 1.15.0. It's still working very well!

**Comment by Nazosan** [comment]
There are different patches for different things.  Some work in this set for some things, but not all.  For example, there is a patched version of the Youtube app that makes it not run through Nintendo's online services (so it can work with 90DNS or Incognito or even on a banned system) and it will not start with this patch set.  The other one arch-box linked to does work however.  It includes all that this does plus more.  There's no reason or benefit to stay back on an older patch set as it won't achieve anything useful to do so.

**Comment by eXhumer** [comment]
I was away for university so I couldn't update my repo, but it has been updated now.
