### ISSUE TITLE
Sigpatches in stock mode

### ISSUE THREAD

**Issue by Owen-sys** [eXhumer/patches#3]
we dont really have easy access to our dumped games when were banned so we cant play it without cfw but if a crash or something to requires you to hard reset means you are gonna have to innject it again. But yes ik cartridges and portable injectors exist but i want some of my digital games to work as well in stock mode (normal firmware)((Vanilla)) is there any way to put sig patches in stock mode?

**Comment by eXhumer** [comment]
No. Sigpatches are CFW only.
