### ISSUE TITLE
12.0.0|AMS M.19.0|E Some games not launching with latest sigpatches

### ISSUE THREAD

**Issue by johnnydunlop** [eXhumer/patches#4]
Hi,

I have applied Firmware 12.0, updated to AMS 19 and applied latest sigpatches from here and some games are not launching with Unable to start software.

Pokemon Sword
BOTW

Some work such as Super Mario 3d world and Super Smash Bros

**Comment by TheDogMatt** [comment]
Im having the Same issue Xenoblade And other games are not working.

**Comment by SirSharpest** [comment]
Same here, "could not start the software" errors.

**Comment by eXhumer** [comment]
Hello. I am aware. I need to investigate this further. I think this is related to ES patches and as a result, eShop backups titles fail to run. The FS/Loader patches should be working as expected. Homebrew titles like Tinfoil and XCI installed titles will still work.

**Comment by Bur0ri** [comment]
> Hello. I am aware. I need to investigate this further. I think this is related to ES patches and as a result, eShop backups titles fail to run. The FS/Loader patches should be working as expected. Homebrew titles like Tinfoil and XCI installed titles will still work.

Tinfoil makes my whole console crash instead

**Comment by eXhumer** [comment]
> > Hello. I am aware. I need to investigate this further. I think this is related to ES patches and as a result, eShop backups titles fail to run. The FS/Loader patches should be working as expected. Homebrew titles like Tinfoil and XCI installed titles will still work.
> 
> Tinfoil makes my whole console crash instead

What is the build ID of atmosphere that you are using? Make sure you are using c67c29eb.

**Comment by TheDogMatt** [comment]
> 
> 
> > > Hello. I am aware. I need to investigate this further. I think this is related to ES patches and as a result, eShop backups titles fail to run. The FS/Loader patches should be working as expected. Homebrew titles like Tinfoil and XCI installed titles will still work.
> > 
> > 
> > Tinfoil makes my whole console crash instead
> 
> What is the build ID of atmosphere that you are using? Make sure you are using c67c29eb.

Mine Crashes with Tinfoil as Well I'm Using the latest version of atmophere

**Comment by Bur0ri** [comment]
> > > Hello. I am aware. I need to investigate this further. I think this is related to ES patches and as a result, eShop backups titles fail to run. The FS/Loader patches should be working as expected. Homebrew titles like Tinfoil and XCI installed titles will still work.
> > 
> > 
> > Tinfoil makes my whole console crash instead
> 
> What is the build ID of atmosphere that you are using? Make sure you are using c67c29eb.

Where can I find that? All I know is that I'm using 0.19.0

**Comment by eXhumer** [comment]
In the Atmosphere ZIP file name, atmosphere-0.19.0-master-c67c29eb+hbl-2.4.1+hbmenu-3.4.0.zip

**Comment by Bur0ri** [comment]
> In the Atmosphere ZIP file name, atmosphere-0.19.0-master-c67c29eb+hbl-2.4.1+hbmenu-3.4.0.zip

Yeah I just found it, I'm gonna reinstall it rn

**Comment by Bur0ri** [comment]
It works now, thanks.

**Comment by V5rov** [comment]
Hello, Tinfoil works with me, but when I try to start any other like Luigi's mansion Zelda etc. it says : could not start software. please try again from the HOME Menu. What should I do?

**Comment by jpdc016** [comment]
can someone guide me where can i download latest sigpatch? currently at 12.0 please brothers

**Comment by Philki99** [comment]
> Hello, Tinfoil works with me, but when I try to start any other like Luigi's mansion Zelda etc. it says : could not start software. please try again from the HOME Menu. What should I do?

Same Problem here

**Comment by Bur0ri** [comment]
I just downgraded back to 11.0.1, y'all should too

**Comment by V5rov** [comment]
> 
> 
> I just downgraded back to 11.0.1, y'all should too

how?

**Comment by TheDogMatt** [comment]
> 
> 
> I just downgraded back to 11.0.1, y'all should too

Nah I do not recommend but you can do what ever everything works for me find now expect an few games and even that he said he had to fix some stuff not being able to load some games.

**Comment by Bur0ri** [comment]
> > I just downgraded back to 11.0.1, y'all should too
> 
> Nah I do not recommend but you can do what ever everything works for me find now expect an few games and even that he said he had to fix some stuff not being able to load some games.

I just used Daybreak and it all happened in like a minute, the only compromise is that Game Cards don't work on that firmware

**Comment by Arek75** [comment]
I'm probably gonna downgrade my emunand as well.  Not just for sigpatches, but also need to wait for authors to update certain homebrew utilities (sys-con in my case).

--Arek75

**Comment by SirSharpest** [comment]
Not sure what the difference is but https://github.com/ITotalJustice/patches/releases seems to have a working solution in the latest release.
