### ISSUE TITLE
12.0.3 needs new FS

### ISSUE THREAD

**Issue by ii0606226** [eXhumer/patches#7]
`fb72224` only added loader patches, but no FS, making the supported versions `AMS 0.19.4 / FW 12.0.2` and not advertised `AMS 0.19.4 / FW 12.0.3`

**Comment by eXhumer** [comment]
C86762BE19A51FA0C737AE921A816846605A64739523B4894F847BBED59E31EA & E1E8D3D6A2FE0B102CC79F8310EEEF66E5D14BCA2ED73454455FD87C615EEDC0 added
